services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - URL=0.0.0.0
      - REDIS_URI=redis://redis:6379
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
